config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :searches, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  scope :search, ->q{where "name LIKE ?", "%#{q}%"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    if request.xhr?
      @users = User.search(params[:name])

      render json: {
        search_result: render_to_string(@users)
      }, status: :ok
    else
      @users = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: {
        user_data: render_to_string(@user)
      }, status: :ok
    else
      render error, status: :unauthorized
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/index.html.erb
<%= form_tag searches_path, method: :get do %>
  <%= text_field_tag :q, params[:name],
    class: "search-box", autocomplete: :off %>
  <span>
    <%= button_tag "search" %>
    <%= link_to "Back to index", users_path %>
  </span>
<% end %>
<br><br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody class="user-table">
    <%= render @users %>
  </tbody>
</table>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= link_to 'Destroy', user, method: :delete, data: {id: user.id},
    class: "destroy" %></td>
</tr>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p>
  We have total <span class="users-size"><%= @users.size %></span> users!
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>
<br>
<h1>New User</h1>
<%= render 'form', user: @user %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>